import { Sidebar } from "@/components/sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col bg-neutral-100 p-3 text-neutral-900 dark:bg-neutral-900 dark:text-white">
          <header className="mb-3 border-b pb-3">
            <h1 className="text-center text-xl">
              Poke
              <span className="text-red-500">Dex</span>
            </h1>
          </header>
          <div className="flex flex-row">
            <Sidebar />
            <div className="flex min-h-screen w-full flex-col space-y-6 p-6">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
